name: 🚧 Project Item
description: Create an issue for a project.  (Mostly for project maintainers)
title: "🚧 Project Item - <title>"
body:
- type: checkboxes
  attributes:
    label: I have done the items below . . .
    description: Please make sure to do the items below.
    options:
    - label: I have updated the title by replacing the '**_<title_**>' section.
      required: true

- type: textarea
  attributes:
    label: |
      ---
      Description
    description: A description of feature/change in the user's perspective
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: |
      The list of items and checkboxes of things that need to be finished for the definition of done.
      Add more items as needed . . .
    value: |
      **This issue is finished when:**
      1. [ ] Code documentation added if required
      2. [ ] Unit tests added
      3. [ ] All unit tests pass
  validations:
    required: true
    render: markdown

- type: checkboxes
  attributes:
    label: ToDo Items
    description: Complete the following items before asking for a PR review
    options:
    - label: Draft pull request created and linked to this issue
    - label: Priority label added to issue (prio-low, prio-medium, or prio-high)
    - label: Issue linked to the proper project
    - label: Issue linked to proper milestone
    - label: Unit tests have been written and/or adjusted for code additions or changes
    - label: All unit tests pass

- type: textarea
  attributes:
    label: Issue Dependencies
    placeholder: |
      No Issue Dependencies
      Example:
        #10 Create new class
        #20 Add unit tests to service
        #30 Cleanup code in UI
    description: |
      A list of issues that are dependencies of this issue and need to be finishes first
      Use the '#\<number\>' syntax to link to an issue
  validations:
    required: false

- type: textarea
  attributes:
    label: Related Work
    placeholder: |
      No Related Work Items Added
      Example:
        #10 Create new class
        #20 Add unit tests to service
        #30 Cleanup code in UI
    description: |
      A list of issues that are related to this issue but that is not a dependency
      Use the '#\<number\>' syntax to link to an issue
  validations:
    required: false    