name: ✅Build Status Check


on:
  workflow_dispatch:
  pull_request:
    branches:
    - master
    - preview


jobs:
  determine_build_config:
    name: Determine Build Configuration
    runs-on: ubuntu-latest
    outputs:
      build-config: ${{ steps.get-build-config.outputs.build-config }}
    steps:
      - name: Get Build Config
        id: get-build-config
        shell: pwsh
        run: |
          # If the destination branch that the pull request is merging into is the master, do a release build
          if ( "${{ github.base_ref }}" -eq "master") {
            "build-config=Release" >> $env:GITHUB_OUTPUT;
          } else { # Any other branch than master, do a debug build
            "build-config=Debug" >> $env:GITHUB_OUTPUT;
          }

  # Build Main Projects
  build_project:
    name: Build Project
    needs: [determine_build_config]
    uses: KinsonDigital/Infrastructure/.github/workflows/build-csharp-project.yml@v4.3.0
    with:
      project-name: "CASL"
      build-config: ${{ needs.determine_build_config.outputs.build-config }}
      net-sdk-version: 7.0.203

  build_tests_project:
    name: Build Tests Project
    needs: [determine_build_config]
    uses: KinsonDigital/Infrastructure/.github/workflows/build-csharp-project.yml@v4.3.0
    with:
      project-name: "CASLTests"
      build-config: ${{ needs.determine_build_config.outputs.build-config }}
      net-sdk-version: 7.0.302
