name: Production Release Version Status Check

env:
  PROJECT_NAME: CASL

on:
  workflow_dispatch:
  pull_request:
    types: [ synchronize ]
    branches: [ master ]

jobs:
  Validate_Prod_Version_Status_Check:
    name: Validate Production Version Status Check
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Version From Project File
      id: get-version
      uses: KinsonDigital/vget@v0.4.0
      with:
        repo-owner-and-name: '${{ github.repository }}'
        branch: '${{ github.ref }}'
        relative-file-path: '${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate Production Version Value
      uses: actions/github-script@v4
      with:
        script: |
          const script = require('./.github/workflows/status-check-scripts/prod-version-status-check.js');
          let version = '${{ steps.get-version.outputs.version }}';
          let scriptResult = script({version});

          if (scriptResult.failed === true) {
            core.setFailed(scriptResult.error);
          } else {
            console.log(`The version 'v${version}' is valid!!`);
          }
