name: 🚀 Release
run-name: ${{ vars.PROJECT_NAME }} ${{ inputs.release-type }} Release ${{ inputs.dry-run == true && '(Dry Run)' || '' }}


defaults:
  run:
    shell: pwsh


permissions:
  contents: write # for creating releases
  issues: read # for milestone checks
  pull-requests: write


env:
  CS_PROJ_FILE_NAME: ${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.csproj


on:
  workflow_dispatch:
    inputs:
      release-type:
        description: The type of release.  Choose 'Preview' or 'Production'.
        required: true
        type: choice
        options: [Preview, Production]
      dry-run:
        description: Dry Run - Check to run the workflow without creating a release.
        required: false
        default: false
        type: boolean


jobs:
  get_and_validate_version:
    name: Get And Validate Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Get Version
        id: get-version
        uses: KinsonDigital/Infrastructure/actions/get-version@9c4f1702ed7e5f785415d7db14796b1dde7c6a16 #v17.2.0
        with:
          version-file-path: "${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.csproj"
          cache-enabled: false

      - name: Validate Version
        id: validate-version
        uses: KinsonDigital/Infrastructure/actions/validate-version@9c4f1702ed7e5f785415d7db14796b1dde7c6a16 #v17.2.0
        with:
          version: "v${{ steps.get-version.outputs.version }}"
          release-type: "${{ inputs.release-type }}"
          cache-enabled: false


  validate_release:
    name: Validate Release
    needs: [get_and_validate_version]
    uses: KinsonDigital/Infrastructure/.github/workflows/validate-release.yml@ccacf172bbbdd78b8a36992948b0c8bef008404c # v18.0.0
    with:
      owner-name: ${{ vars.ORGANIZATION_NAME }}
      repo-name: ${{ vars.PROJECT_NAME }}
      release-type: ${{ inputs.release-type }}
      version: ${{ needs.get_and_validate_version.outputs.version }}
      relative-release-notes-file-path: "ReleaseNotes/${{ inputs.release-type }}Releases/${{ vars.RELEASE_NOTES_FILE_NAME_PREFIX }}v${{ needs.get_and_validate_version.outputs.version }}.md"
      is-dotnet-project: true
    secrets:
      cicd-pat: ${{ secrets.CICD_TOKEN }}


  build_casl:
    name: Build CASL Status Check
    needs: [validate_release]
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
        build_config: [Release]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 #v5.4.0
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Build
        env:
          WORKSPACE: ${{ github.workspace }}
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          BUILD_CONFIG: ${{ matrix.build_config }}
        run: dotnet build "$($env:WORKSPACE)/$($env:PROJECT_NAME)/$($env:PROJECT_NAME).csproj" -c "$env:BUILD_CONFIG";


  run_casl_tests:
    name: Run CASL Tests
    needs: [validate_release]
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
        build_config: [Debug, Release]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 #v5.4.0
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Tests
        env:
          WORKSPACE: ${{ github.workspace }}
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          BUILD_CONFIG: ${{ matrix.build_config }}
        run: dotnet test "$($env:WORKSPACE)/Testing/$($env:PROJECT_NAME)Testing/$($env:PROJECT_NAME)Testing.csproj" -c "$env:BUILD_CONFIG";


  # run_release:
  #   name: Performing ${{ inputs.release-type }} Release of ${{ vars.PROJECT_NAME }} (${{ inputs.release-type == 'Production' && 'Release' || 'Debug' }})
  #   needs: [build_casl, run_casl_tests, get_and_validate_version]
  #   if: ${{ inputs.dry-run == false }}
  #   uses: KinsonDigital/Infrastructure/.github/workflows/dotnet-lib-release.yml@ccacf172bbbdd78b8a36992948b0c8bef008404c # v18.0.0
  #   with:
  #     project-name: "${{ vars.PROJECT_NAME }}"
  #     release-type: "${{ inputs.release-type }}"
  #     net-sdk-version: "${{ vars.NET_SDK_VERSION }}"
  #     build-config: ${{ inputs.release-type == 'Production' && 'Release' || 'Debug' }}
  #     version: ${{ needs.get_and_validate_version.outputs.version }}
  #     transpile-readme: true
  #     release-notes-file-path: "${{ github.workspace }}/ReleaseNotes/${{ inputs.release-type }}Releases/${{ vars.RELEASE_NOTES_FILE_NAME_PREFIX }}v${{ needs.get_and_validate_version.outputs.version }}.md"
  #   secrets:
  #     cicd-pat: "${{ secrets.CICD_TOKEN }}"
  #     nuget-user: "${{ secrets.NUGET_USER }}"


  send_release_announcements:
    name: Send Release Announcements
    runs-on: ubuntu-latest
    # needs: [get_and_validate_version, validate_release, build_casl, run_casl_tests, run_release]
    needs: [get_and_validate_version, validate_release, build_casl, run_casl_tests]
    if: ${{ inputs.dry-run == false }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      # - name: Send X Release Announcement
      #   uses: KinsonDigital/Infrastructure/actions/send-x-release-announcement@9c4f1702ed7e5f785415d7db14796b1dde7c6a16 #v17.2.0
      #   with:
      #     repo-owner: ${{ vars.ORGANIZATION_NAME }}
      #     project-name: ${{ vars.PROJECT_NAME }}
      #     version: ${{ needs.get_and_validate_version.outputs.version }}
      #     local-post-template-file-path: "${{ github.workspace }}/templates/${{ vars.RELEASE_POST_TEMPLATE_FILE_NAME }}"
      #     discord-invite-code: ${{ vars.DISCORD_INVITE_CODE }}
      #     website-url: ${{ vars.WEBSITE_URL }}
      #     access-token-key: ${{ secrets.X_ACCESS_TOKEN_KEY }}
      #     access-token-secret: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
      #     consumer-api-key: ${{ secrets.X_CONSUMER_API_KEY }}
      #     consumer-api-secret: ${{ secrets.X_CONSUMER_API_SECRET }}
      #     cache-enabled: false
      #     github-token: ${{ secrets.CICD_TOKEN }}

      # - name: Send Bluesky Release Announcement
      #   uses: KinsonDigital/Infrastructure/actions/send-bluesky-release-announcement@9c4f1702ed7e5f785415d7db14796b1dde7c6a16 #v17.2.0
      #   with:
      #     repo-owner: ${{ vars.ORGANIZATION_NAME }}
      #     project-name: ${{ vars.PROJECT_NAME }}
      #     version: ${{ needs.get_and_validate_version.outputs.version }}
      #     website-url: ${{ vars.WEBSITE_URL }}
      #     local-post-template-file-path: "${{ github.workspace }}/templates/${{ vars.RELEASE_POST_TEMPLATE_FILE_NAME }}"
      #     discord-invite-code: ${{ vars.DISCORD_INVITE_CODE }}
      #     service: ${{ vars.BLUESKY_SERVICE }}
      #     identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
      #     password: ${{ secrets.BLUESKY_APP_PASSWORD }}
      #     cache-enabled: false
      #     github-token: ${{ secrets.CICD_TOKEN }}

  
  process_milestone:
    name: Process Milestone
    # needs: [get_and_validate_version, validate_release, build_casl, run_casl_tests, run_release]
    needs: [get_and_validate_version, validate_release, build_casl, run_casl_tests]
    if: ${{ inputs.dry-run == false }}
    uses: KinsonDigital/Infrastructure/.github/workflows/process-milestone.yml@ccacf172bbbdd78b8a36992948b0c8bef008404c # v18.0.0
    with:
      owner-name: ${{ vars.ORGANIZATION_NAME }}
      repo-name: ${{ vars.PROJECT_NAME }}
      version: ${{ needs.get_and_validate_version.outputs.version }}
    secrets:
      cicd-pat: ${{ secrets.CICD_TOKEN }}
