name: ✅ Unit Testing Status Check
run-name: ✅ Unit Testing Status Check (${{ github.base_ref }} branch)


permissions:
  contents: read


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: [main, preview]


jobs:
  run_casl_tests:
    name: Run CASL Tests
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
        build_config: [Debug, Release]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 #v5.4.0
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Tests
        env:
          WORKSPACE: ${{ github.workspace }}
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          BUILD_CONFIG: ${{ matrix.build_config }}
        run: dotnet test "$($env:WORKSPACE)/Testing/$($env:PROJECT_NAME)Testing/$($env:PROJECT_NAME)Testing.csproj" -c "$env:BUILD_CONFIG";


  unit_test_status_check:
    name: ✅ Unit Testing Status Check
    needs: [run_casl_tests]
    runs-on: ubuntu-latest
    steps:
      - run: Write-Host "All unit test status checks passed.";
