name: ✅ Unit Testing Status Check
run-name: ✅ Unit Testing Status Check (${{ github.base_ref }} branch)


defaults:
  run:
    shell: pwsh


on:
  pull_request_target:
    branches: [main, preview]


jobs:
  run_casl_tests:
    name: Run CASL Tests
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
        build_config: [Debug, Release]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 #v5.4.0
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Tests
        env:
          WORKSPACE: ${{ github.workspace }}
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          BUILD_CONFIG: ${{ matrix.build_config }}
        run: dotnet test "$env.WORKSPACE/Testing/$($env.PROJECT_NAME)Testing/$($env.PROJECT_NAME)Testing.csproj" -c $env.BUILD_CONFIG;
