name: ✅Unit Testing Status Check
run-name: "Unit Testing Status Check (Not Required)"


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    paths-ignore:
      - "**.cs"
      - "**.csproj"


jobs:
  run_tests:
    name: Unit Testing Status Check (Not Required)
    runs-on: ubuntu-latest
    steps:
    - name: Print Message
      run: 'echo "Status Check Not Required"'
