name: ✅Unit Testing Status Check
run-name: ✅Unit Testing Status Check (${{ github.base_ref }} branch)


defaults:
  run:
    shell: pwsh


on:
  pull_request_target:
    branches: [main, preview]


jobs:
  run_tests:
    name: ${{ vars.PROJECT_NAME }} Test Status Check
    uses: KinsonDigital/Infrastructure/.github/workflows/run-csharp-tests.yml@v13.6.3
    with:
      project-name: "${{ vars.PROJECT_NAME }}Tests"
      build-config: Debug
      net-sdk-version: "${{ vars.NET_SDK_VERSION }}"
      checkout-repository: ${{ github.event.pull_request.head.repo.full_name }}
      checkout-ref: ${{ github.event.pull_request.head.ref }}
    secrets:
      cicd-pat: ${{ secrets.CICD_TOKEN }}
