name: Preview Version Status

env:
  PROJECT_NAME: CASL
  BUILD_CONFIG: Debug
  RELEASE_NAME: Preview
  NET_SDK_VERSION: 5.0.x # Changing this means changing ARTIFACT_FOLDER_NAME
  ARTIFACT_FOLDER_NAME: '5.0' # Changing this means changing NET_SDK_VERSION

on:
  workflow_dispatch:
  pull-request:
    types: [synchronize]
    branches: [ workflow-testing ]
    paths-ignore:
      - ".github/**"
      - 'Documentation/**'
      - '.editorconfig'
      - '*.runsettings'
      - '.gitattributes'
      - '.gitignore'
      - '*.md'
      - '.vscode/**'

jobs:
  Check_Preview_Version_Status:
    name: Check Preview Version Status
    runs-on: windows-latest
    steps:
    - name: Get Version From Project File
      id: get-version
      uses: KinsonDigital/vget@v0.3.0
      with:
        repo-owner-and-name: '${{ github.repository }}'
        branch: '${{ github.ref }}'
        relative-file-path: '${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj'
        user-name: 'kinsondigital@gmail.com'
        password: ${{ secrets.REPO_PASSWORD }}
        contains: '-preview.'